# Generated by Django 3.1.6 on 2021-02-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='special_files',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
