# Generated by Django 3.1.6 on 2021-02-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210209_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_nr',
            field=models.CharField(max_length=20),
        ),
    ]
