# Generated by Django 3.1.6 on 2021-02-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210210_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_nr',
            field=models.CharField(max_length=20),
        ),
    ]
